export const GET_CURRENT_CITY_LOCATION = "GET_CURRENT_CITY_LOCATION";
export const GET_CURRENT_CITY_FORECAST ="GET_CURRENT_CITY_FORECAST";
export const GET_SEARCHED_CITY_FORECAST ="GET_SEARCHED_CITY_FORECAST";
export const GET_ERRORS = "GET_ERRORS";
export const CURRENT_CITY_LOADING = "CURRENT_CITY_LOADING";
export const CURRENT_CITY_FORECAST_LOADING = "CURRENT_CITY_FORECAST_LOADING";
export const SEARCHED_CITY_FORECAST_LOADING = "SEARCHED_CITY_FORECAST_LOADING";
